name: Create Trello Webhook

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Create Trello Webhook
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
      run: |
        python create_trello_webhook.py
