name: Sync Trello and Motion

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Cache dependencies
      uses: actions/cache@v4  # Update to v4 for Node.js 20
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run sync script
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        TRELLO_LIST_NAME: ${{ secrets.TRELLO_LIST_NAME }}
        MOTION_API_KEY: ${{ secrets.MOTION_API_KEY }}
        MOTION_WORKSPACE_ID: ${{ secrets.MOTION_WORKSPACE_ID }}
      run: |
        python sync_trello_motion.py
