name: Sync Motion and Trello

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run Sync Motion and Trello script
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
        TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        TRELLO_LIST_NAME: ${{ secrets.TRELLO_LIST_NAME }}
        MOTION_API_KEY: ${{ secrets.MOTION_API_KEY }}
        MOTION_WORKSPACE_ID: ${{ secrets.MOTION_WORKSPACE_ID }}
      run: |
        python sync_trello_motion.py
      